# Default initial positions for h1_description's ros2_control fake system

initial_positions:
  left_ankle_joint: 0
  left_hip_pitch_joint: 0
  left_hip_roll_joint: 0
  left_hip_yaw_joint: 0
  left_knee_joint: 0
  right_ankle_joint: 0
  right_hip_pitch_joint: 0
  right_hip_roll_joint: 0
  right_hip_yaw_joint: 0
  right_knee_joint: 0